import type { CardData } from "@/lib/types";

/** ממיר כרטיס לשורת מסד הנתונים. משותף ל-API של הלקוח ולפעולות הניהול. */
export function cardToDatabaseRow(card: CardData | ReturnType<typeof import("@/lib/validation").cardSchema.parse>, userId: string) {
  return {
    user_id: userId,
    slug: card.slug,
    business_name: card.businessName,
    owner_name: card.ownerName,
    role_title: card.roleTitle,
    slogan: card.slogan,
    bio: card.bio,
    cta_label: card.ctaLabel,
    phone: card.phone,
    whatsapp: card.whatsapp,
    email: card.email,
    website: card.website,
    address: card.address,
    avatar_url: card.avatarUrl,
    cover_url: card.coverUrl,
    logo_url: card.logoUrl,
    logo_shape: card.logoShape,
    video_url: card.videoUrl,
    gallery: card.gallery,
    files: card.files,
    primary_color: card.primaryColor,
    accent_color: card.accentColor,
    button_color: card.buttonColor,
    heading_color: card.headingColor,
    body_text_color: card.bodyTextColor,
    background_preset: card.backgroundPreset,
    template: card.template,
    is_published: card.isPublished,
    allow_indexing: card.allowIndexing,
    seo_title: card.seoTitle,
    seo_description: card.seoDescription,
    social_image_url: card.socialImageUrl,
    area_served: card.areaServed,
    cover_alt: card.coverAlt,
    logo_alt: card.logoAlt,
    avatar_alt: card.avatarAlt,
    social_links: card.socialLinks,
    quick_actions: card.quickActions,
    quick_actions_limit: card.quickActionsLimit,
    smart_buttons: card.smartButtons,
    widgets: card.widgets,
    contact_form_title: card.contactFormTitle,
    contact_form_success_message: card.contactFormSuccessMessage,
    contact_form_fields: card.contactFormFields,
    gallery_style: card.galleryStyle,
    tracking: card.tracking,
    vcard: card.vcard,
    services: card.services,
    testimonials: card.testimonials,
    business_hours: card.businessHours,
    updated_at: new Date().toISOString(),
  };
}
