import type { AnalyticsSummary, CardData, Viewer } from "@/lib/types";

// ההתנסות בהדגמה מתחילה בכל טעינה, כדי שהטיימר יציג תמיד מצב חי ותקין.
const demoTrialEndsAt = () => new Date(Date.now() + 9 * 86400000).toISOString();

// role נשאר "customer": כשאין Supabase כל מבקר אנונימי מקבל את ה‑Viewer הזה,
// ו‑role: "admin" היה פותח לו את /admin. הרשאת אדמין בהדגמה דורשת דגל מפורש.
export const demoViewer: Viewer = {
  id: "demo-user",
  email: "demo@naimly.local",
  fullName: "נועה כהן",
  role: process.env.DEMO_ADMIN === "true" ? "admin" : "customer",
  plan: "pro",
  subscriptionStatus: "trialing",
  get trialEndsAt() { return demoTrialEndsAt(); },
  trialPending: false,
  demo: true,
};

export const demoCard: CardData = {
  id: "demo-card",
  userId: "demo-user",
  slug: "noa-design",
  businessName: "NOA Studio",
  ownerName: "נועה כהן",
  roleTitle: "מיתוג ועיצוב לעסקים",
  slogan: "מותג מדויק. נוכחות שאי אפשר לפספס.",
  bio: "אני עוזרת לעסקים להפוך רעיון למותג שאנשים זוכרים — משלב האסטרטגיה ועד לנראות שעובדת בכל ערוץ.",
  ctaLabel: "בואו נדבר",
  phone: "050-000-0000",
  whatsapp: "972500000000",
  email: "hello@example.com",
  website: "https://example.com",
  address: "רח׳ החשמונאים 100, תל אביב",
  avatarUrl: "",
  coverUrl: "",
  logoUrl: "",
  logoShape: "rounded",
  videoUrl: "",
  gallery: [],
  files: [],
  primaryColor: "#6d4aff",
  accentColor: "#14d9c4",
  buttonColor: "#6d4aff",
  headingColor: "#142038",
  bodyTextColor: "#53627a",
  backgroundPreset: "aurora",
  template: "spotlight",
  isPublished: true,
  allowIndexing: true,
  seoTitle: "נועה כהן — מיתוג ועיצוב לעסקים",
  seoDescription: "אסטרטגיית מותג, שפה חזותית ועיצוב דיגיטלי לעסקים שרוצים לבלוט.",
  socialImageUrl: "",
  areaServed: "תל אביב והמרכז",
  coverAlt: "רקע ממותג של NOA Studio",
  logoAlt: "לוגו NOA Studio",
  avatarAlt: "נועה כהן, מעצבת וממתגת עסקים",
  socialLinks: [
    { network: "instagram", url: "https://instagram.com" },
    { network: "linkedin", url: "https://linkedin.com" },
    { network: "facebook", url: "https://facebook.com" },
  ],
  quickActions: [
    { id: "qa1", type: "phone", label: "שיחה", value: "050-000-0000" },
    { id: "qa2", type: "whatsapp", label: "WhatsApp", value: "972500000000" },
    { id: "qa3", type: "email", label: "אימייל", value: "hello@example.com" },
    { id: "qa4", type: "save_contact", label: "שמור אותי", value: "" },
    { id: "qa5", type: "waze", label: "Waze", value: "רח׳ החשמונאים 100, תל אביב" },
    { id: "qa6", type: "instagram", label: "Instagram", value: "https://instagram.com" },
  ],
  quickActionsLimit: 6,
  smartButtons: [
    { id: "b1", label: "לתיק העבודות", description: "פרויקטים נבחרים מהשנה האחרונה", action: "url", value: "https://example.com" },
    { id: "b2", label: "קביעת שיחת היכרות", description: "בוחרים זמן שמתאים לכם", action: "booking", value: "https://cal.com" },
  ],
  widgets: [
    { id: "w1", type: "smart_buttons", title: "קישורים חשובים", enabled: true },
    { id: "w2", type: "services", title: "השירותים שלי", enabled: true },
    { id: "w3", type: "gallery", title: "גלריה", enabled: true },
    { id: "w4", type: "video", title: "הכירו את העסק", enabled: true },
    { id: "w5", type: "testimonials", title: "לקוחות מספרים", enabled: true },
    { id: "w6", type: "hours", title: "שעות פעילות", enabled: true },
    { id: "w7", type: "files", title: "קבצים וקטלוגים", enabled: true },
    { id: "w8", type: "contact_form", title: "דברו איתי", enabled: true },
  ],
  contactFormTitle: "רוצה שנחזור אליך?",
  contactFormSuccessMessage: "תודה! הפרטים התקבלו ונחזור אליך בהקדם.",
  contactFormFields: [
    { id: "f1", label: "שם מלא", type: "text", required: true },
    { id: "f2", label: "טלפון", type: "tel", required: true },
    { id: "f3", label: "אימייל", type: "email", required: false },
    { id: "f4", label: "במה אפשר לעזור?", type: "textarea", required: false },
  ],
  galleryStyle: "carousel",
  tracking: { googleAnalyticsId: "", googleTagManagerId: "", metaPixelId: "" },
  cardAddress: {
    country: "ישראל",
    city: "תל אביב",
    street: "החשמונאים",
    houseNumber: "100",
    postalCode: "6713303",
    latitude: "32.0733",
    longitude: "34.7818",
    note: "קומה 3, כניסה ב׳",
  },
  vcard: {
    firstName: "נועה",
    lastName: "כהן",
    phoneSecondary: "03-7654321",
    includePhoto: true,
    fullName: "נועה כהן",
    organization: "NOA Studio",
    title: "מיתוג ועיצוב לעסקים",
    phone: "050-000-0000",
    email: "hello@example.com",
    website: "https://example.com",
    address: "רח׳ החשמונאים 100, תל אביב",
    note: "נשמר מכרטיס הביקור הדיגיטלי של נועה כהן",
  },
  services: [
    { id: "s1", title: "אסטרטגיית מותג", description: "דיוק הקהל, הבידול והמסר לפני שמתחילים לעצב.", price: "החל מ־1,800 ₪" },
    { id: "s2", title: "זהות חזותית", description: "לוגו, צבעוניות, טיפוגרפיה ושפה גרפית שלמה.", price: "החל מ־3,200 ₪" },
    { id: "s3", title: "עיצוב לרשתות", description: "מערכת תבניות גמישה שמייצרת נוכחות עקבית.", price: "החל מ־950 ₪" },
  ],
  testimonials: [
    { id: "t1", name: "מיכל, Studio M", text: "נועה הצליחה לתרגם את העסק שלנו למותג מדויק, נקי וממש זכיר.", rating: 5 },
    { id: "t2", name: "אורי, North Labs", text: "תהליך מקצועי, ברור ומהיר. קיבלנו שפה שמשרתת אותנו בכל מקום.", rating: 5 },
  ],
  businessHours: [
    { day: "א׳–ה׳", hours: "09:00–18:00" },
    { day: "ו׳", hours: "09:00–13:00" },
    { day: "שבת", hours: "סגור" },
  ],
  updatedAt: "2026-09-04T12:00:00.000Z",
};

export const demoAnalytics: AnalyticsSummary = {
  views: 1842,
  clicks: 639,
  leads: 47,
  contactSaves: 126,
  conversionRate: 7.4,
  daily: [
    { date: "29.8", views: 42, clicks: 13 },
    { date: "30.8", views: 55, clicks: 17 },
    { date: "31.8", views: 47, clicks: 19 },
    { date: "1.9", views: 68, clicks: 22 },
    { date: "2.9", views: 81, clicks: 31 },
    { date: "3.9", views: 74, clicks: 28 },
    { date: "4.9", views: 96, clicks: 37 },
  ],
  actions: [
    { label: "WhatsApp", value: 271, percent: 42 },
    { label: "שמירת איש קשר", value: 126, percent: 20 },
    { label: "טלפון", value: 102, percent: 16 },
    { label: "אתר", value: 86, percent: 13 },
    { label: "טופס פנייה", value: 54, percent: 9 },
  ],
};
