import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, BarChart3, Blocks, Bot, Check, ChevronLeft, Clock3, Cookie, LineChart, Link2, MailCheck, MapPinned, MousePointerClick, QrCode, ShieldCheck, Sparkles, WandSparkles, Zap } from "lucide-react";
import { CardPreview } from "@/components/card/card-preview";
import { ProductPlayground } from "@/components/marketing/product-playground";
import { HowItWorks } from "@/components/marketing/how-it-works";
import { LiveDemo } from "@/components/marketing/live-demo";
import { Testimonials } from "@/components/marketing/testimonials";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { brand, plans } from "@/lib/config";
import { demoCard } from "@/lib/demo-data";
import { formatCurrency } from "@/lib/utils";

export const metadata: Metadata = { alternates: { canonical: "/" } };

const bento = [
  { icon: MapPinned, title: "כתובת אחת. שני מסלולי ניווט.", text: "מזינים כתובת והמערכת בונה אוטומטית קישורים תקינים ל־Waze ול־Google Maps.", className: "md:col-span-2" },
  { icon: Blocks, title: "בונה מודולרי", text: "מפעילים, מסתירים ומסדרים ווידג׳טים בלי לגעת בקוד.", className: "" },
  { icon: LineChart, title: "מה באמת עובד", text: "רואים צפיות, לחיצות, שמירות ופניות לפי פעולה.", className: "" },
  { icon: Link2, title: "כל פעולה הופכת לחכמה", text: "טלפון, WhatsApp, מייל, תפריט, קביעת תור, תמונה, קטלוג או כל קישור אחר.", className: "md:col-span-2" },
];
const faqs = [
  ["איך מתחילים אחרי שבוחרים מסלול?", "פותחים חשבון קצר ומאובטח, משלימים תשלום ומקבלים מייל אימות. לאחר מכן נכנסים ישירות לבונה הכרטיס."],
  ["האם שולחים סיסמה במייל?", "לא. סיסמה גלויה במייל אינה בטוחה. המערכת שולחת קישור אימות, ואפשר גם להיכנס בקישור חד־פעמי ללא סיסמה."],
  ["צריך לדעת לעצב או לתכנת?", "לא. בוחרים תבנית, מעלים לוגו וקאבר ומרכיבים את הכרטיס מווידג׳טים. התוצאה מופיעה בזמן אמת."],
  ["מה קורה ל־QR אחרי עדכון?", "הקישור וה־QR נשארים קבועים. אפשר להחליף תוכן, צבעים ופעולות בלי להדפיס מחדש."],
  ["אפשר לחבר כלי פרסום?", "כן. במסלול מקצועי ומעלה אפשר לחבר Google Analytics, Google Tag Manager ו־Meta Pixel, בכפוף להסכמת המבקר לעוגיות."],
];

export default function HomePage() {
  const featuredPlans = plans.filter((plan) => plan.id !== "trial");
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": `${brand.siteUrl}/#organization`, name: `${brand.name} — ${brand.hebrewName}`, url: brand.siteUrl, email: brand.supportEmail }, { "@type": "WebSite", "@id": `${brand.siteUrl}/#website`, name: brand.name, alternateName: brand.hebrewName, url: brand.siteUrl, inLanguage: "he-IL", publisher: { "@id": `${brand.siteUrl}/#organization` } }, { "@type": "SoftwareApplication", name: brand.name, applicationCategory: "BusinessApplication", operatingSystem: "Web", inLanguage: "he-IL", url: brand.siteUrl, offers: plans.filter((plan) => plan.price > 0).map((plan) => ({ "@type": "Offer", price: plan.price, priceCurrency: "ILS", name: plan.name })) }] };
  return <div className="min-h-screen bg-white"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><SiteHeader /><main>
    <section className="relative overflow-hidden bg-[#071225] pb-16 pt-14 text-white sm:pb-24 sm:pt-20">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_12%,rgba(109, 74, 255,.48),transparent_30%),radial-gradient(circle_at_12%_70%,rgba(20, 217, 196,.2),transparent_28%)]" />
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#6ee4d3] to-transparent opacity-60" />
      <div className="container-shell relative grid items-center gap-14 lg:grid-cols-[1.08fr_.92fr]">
        <div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.07] px-3 py-2 text-sm font-bold text-[#8ef3e4]"><Sparkles size={15} />כרטיס דיגיטלי שהופך מבקר לפנייה</span><h1 className="mt-6 text-[clamp(2.8rem,7vw,6.1rem)] font-black leading-[.98] tracking-[-0.06em]">לא עוד דף קישורים.<br /><span className="bg-gradient-to-l from-[#8d7eff] via-[#d7d1ff] to-[#6ee4d3] bg-clip-text text-transparent">מיני־אתר שמוכר.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#b6c1d3] sm:text-xl">מרכיבים כרטיס חכם מווידג׳טים, מחברים כל פעולה בלחיצה ורואים אילו לקוחות צפו, לחצו והשאירו פרטים — בלי מעצב ובלי מתכנת.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup?plan=pro" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-[#7160eb] px-7 font-extrabold text-white shadow-[0_18px_50px_rgba(109, 74, 255,.38)] hover:bg-[#6150db]">מתחילים לבנות בחינם <ArrowLeft size={18} /></Link><Link href="/noa-design" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/[.06] px-7 font-bold text-white hover:bg-white/10">צפייה בכרטיס חי</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm text-[#a9b6ca]">{["14 ימי ניסיון", "ללא כרטיס אשראי", "מוכן לנייד ולדפוס"].map((item) => <span key={item} className="inline-flex items-center gap-1.5"><Check size={15} className="text-[#6ee4d3]" />{item}</span>)}</div></div>
        <div className="relative mx-auto w-full max-w-[470px]"><div className="absolute -inset-10 rounded-full bg-[#6b58e4]/25 blur-3xl" /><div className="relative grid grid-cols-[80px_1fr] items-center gap-3"><div className="grid gap-3">{[{ icon: Blocks, label: "ווידג׳טים" }, { icon: MapPinned, label: "ניווט" }, { icon: QrCode, label: "QR" }, { icon: BarChart3, label: "נתונים" }].map(({ icon: Icon, label }, index) => <div key={label} className={`grid min-h-20 place-items-center rounded-2xl border border-white/10 bg-white/[.07] text-center backdrop-blur ${index === 1 ? "translate-x-2" : ""}`}><Icon size={20} className="text-[#79ead9]" /><span className="text-[11px] font-bold text-white/65">{label}</span></div>)}</div><div className="rounded-[38px] border-[9px] border-[#151b28] bg-white shadow-[0_35px_100px_rgba(0,0,0,.45)]"><div className="max-h-[600px] overflow-hidden rounded-[27px]"><CardPreview card={demoCard} compact /></div></div></div><div className="absolute -bottom-5 left-0 flex items-center gap-3 rounded-2xl border border-white/10 bg-[#111d33]/95 p-3 shadow-2xl backdrop-blur"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#6ee4d3]/15 text-[#6ee4d3]"><MousePointerClick size={19} /></span><span><strong className="block text-sm">כל לחיצה נמדדת</strong><small className="text-white/45">בלי לנחש מה עובד</small></span></div></div>
      </div>
      <div className="container-shell relative mt-16"><div className="flex flex-wrap justify-center gap-2 border-y border-white/10 py-5 text-xs font-bold text-white/55">{["תמונת קאבר", "לוגו וצורה", "3 / 6 / 9 פעולות", "Waze + Maps", "כפתורים חכמים", "קרוסלה", "YouTube", "טופס דינמי", "Meta Pixel", "Google Analytics"].map((item) => <span key={item} className="rounded-full bg-white/[.055] px-3 py-2">{item}</span>)}</div></div>
    </section>

    <section className="py-20 sm:py-28"><div className="container-shell"><div className="mx-auto max-w-3xl text-center"><span className="eyebrow"><WandSparkles size={15} />נבנה סביב העסק, לא סביב תבנית</span><h2 className="mt-5 text-4xl font-black tracking-[-0.05em] sm:text-6xl">כל מה שהלקוח צריך — בדיוק בסדר הנכון.</h2><p className="mt-5 text-lg leading-8 text-[#607087]">הכרטיס מתחיל פשוט וגדל לפי הצורך: פעולות, תוכן, לידים ומדידה באותו ממשק.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{bento.map(({ icon: Icon, title, text, className }) => <article key={title} className={`group relative overflow-hidden rounded-[26px] border border-[#e1e6ee] bg-[#f7f8fc] p-7 ${className}`}><div className="absolute -left-8 -top-10 h-28 w-28 rounded-full bg-[#6654df]/10 blur-2xl" /><span className="relative grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#6d4aff] shadow-sm"><Icon size={22} /></span><h3 className="relative mt-6 text-xl font-extrabold">{title}</h3><p className="relative mt-2 max-w-xl leading-7 text-[#607087]">{text}</p></article>)}</div></div></section>

    <section id="builder-preview" className="overflow-hidden bg-[#0b1020] py-20 text-white sm:py-28"><div className="container-shell"><div className="mb-12 grid gap-5 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-sm font-bold text-[#80eadb]"><Zap size={15} />נסו את המוצר</span><h2 className="mt-5 text-4xl font-black tracking-[-0.05em] sm:text-6xl">הכרטיס משתנה מול העיניים.</h2></div><p className="max-w-2xl text-lg leading-8 text-[#aebbd0]">הפעילו ווידג׳טים והחליפו צבע מותג. זו אותה לוגיקה פשוטה שהלקוח מקבל במערכת הניהול.</p></div><ProductPlayground /></div></section>

    <section className="py-20 sm:py-28"><div className="container-shell"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="eyebrow"><MailCheck size={15} />מהרכישה לכרטיס פעיל</span><h2 className="mt-5 text-4xl font-black tracking-[-0.05em] sm:text-5xl">פשוט ללקוח. בטוח לעסק.</h2><p className="mt-4 text-lg leading-8 text-[#607087]">בוחרים מסלול, פותחים חשבון קצר, משלמים ונכנסים ישר לבונה. המייל משמש לזיהוי ולאימות מאובטח.</p></div><ol className="grid gap-3">{[["01", "בחירת מסלול", "מחיר ברור והבדלים שקל להבין."], ["02", "חשבון ותשלום", "אימות באימייל ועמוד סליקה מאובטח."], ["03", "בנייה בווידג׳טים", "לוגו, קאבר, פעולות, תוכן וטופס."], ["04", "פרסום ומדידה", "קישור, QR, פניות ואנליטיקה." ]].map(([number, title, text]) => <li key={number} className="grid grid-cols-[58px_1fr_auto] items-center gap-4 rounded-2xl border border-[#e1e6ee] p-5"><span className="text-2xl font-black text-[#6d4aff]">{number}</span><span><strong className="block">{title}</strong><span className="mt-1 block text-sm text-[#6b778d]">{text}</span></span><ChevronLeft size={18} className="text-[#a1aaba]" /></li>)}</ol></div></div></section>

      <HowItWorks />
      <LiveDemo card={demoCard} videoId={process.env.NEXT_PUBLIC_DEMO_VIDEO_ID} />
    <section className="bg-[#f3f5fa] py-20 sm:py-28"><div className="container-shell"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="eyebrow">מחיר השקה תחרותי</span><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] sm:text-5xl">מתחילים קטן. משדרגים לפי התוצאה.</h2></div><Link href="/pricing" className="button-ghost self-start">השוואה מלאה <ArrowLeft size={17} /></Link></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{featuredPlans.map((plan) => <article key={plan.id} className={`relative flex flex-col rounded-[26px] border bg-white p-7 shadow-[0_12px_35px_rgba(11,24,48,.07)] ${plan.badge ? "border-[#6d4aff] ring-4 ring-[#6d4aff]/8" : "border-[#dfe4ec]"}`}>{plan.badge && <span className="absolute -top-3 right-6 rounded-full bg-[#6d4aff] px-3 py-1 text-xs font-bold text-white">{plan.badge}</span>}<h3 className="text-xl font-extrabold">{plan.name}</h3><p className="mt-2 min-h-12 text-sm text-[#607087]">{plan.description}</p><p className="mt-5"><strong className="text-5xl tracking-tight">{formatCurrency(plan.price)}</strong><span className="text-sm text-[#6b778d]"> / לחודש</span></p><ul className="my-6 grid flex-1 gap-3 text-sm">{plan.features.map((feature) => <li key={feature} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-[#0a9b81]" />{feature}</li>)}</ul><Link href={`/signup?plan=${plan.id}`} className={plan.badge ? "button-primary w-full" : "button-secondary w-full"}>בחירת מסלול</Link></article>)}</div><p className="mt-5 text-center text-sm text-[#718096]">14 ימי ניסיון ללא חיוב. המחירים לפני חיבור ספק הסליקה הסופי וניתנים לעדכון במקום מרכזי אחד.</p></div></section>

      <Testimonials />
    <section id="faq" className="scroll-mt-20 py-20 sm:py-28"><div className="container-shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><span className="eyebrow">שאלות חשובות</span><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] sm:text-5xl">ברור לפני שמתחילים.</h2><div className="mt-7 grid gap-3 text-sm text-[#607087]"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-[#0a9b81]" />אימות מאובטח</span><span className="flex items-center gap-2"><Cookie size={17} className="text-[#0a9b81]" />מדידה רק לאחר הסכמה</span><span className="flex items-center gap-2"><Clock3 size={17} className="text-[#0a9b81]" />עדכון עצמי בכל רגע</span></div></div><div className="grid gap-3">{faqs.map(([question, answer], index) => <details key={question} className="group card-surface px-5 py-1" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 font-bold">{question}<span className="text-xl text-[#6d4aff] group-open:rotate-45">+</span></summary><p className="border-t border-[#e8ecf3] py-4 text-sm leading-7 text-[#607087]">{answer}</p></details>)}</div></div></section>

    <section className="pb-20"><div className="container-shell"><div className="relative overflow-hidden rounded-[34px] bg-[linear-gradient(115deg,#6d4aff,#384ac9_55%,#0c9d8b)] p-8 text-white shadow-2xl sm:p-14"><div className="absolute -left-12 -top-12 h-40 w-40 rounded-full border-[28px] border-white/10" /><div className="relative grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-sm font-bold text-[#bff7ef]"><Bot size={17} />המערכת עושה את העבודה הטכנית</div><h2 className="mt-3 text-4xl font-black tracking-[-0.05em] sm:text-5xl">העסק שלך יכול להיות בכיס של כל לקוח עוד היום.</h2></div><Link href="/signup?plan=pro" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-white px-7 font-extrabold text-[#5134cc] shadow-xl">מתחילים לבנות <ArrowLeft size={18} /></Link></div></div></div></section>
  </main><SiteFooter /></div>;
}
