-- ==================================================================
-- NAIMLY — כל המיגרציות בקובץ אחד, לפי הסדר
-- נוצר אוטומטית: npm run db:bundle
-- להדבקה ב-Supabase → SQL Editor → Run
-- ==================================================================

-- ----------------------------------------------------------------
-- 001_initial_schema.sql
-- ----------------------------------------------------------------

-- NAIMLY: סכמת Production ראשונית ל-Supabase/PostgreSQL
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  full_name text not null default '',
  role text not null default 'customer' check (role in ('customer', 'admin')),
  plan_id text not null default 'trial' check (plan_id in ('trial', 'basic', 'pro', 'premium')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9-]{3,60}$'),
  business_name text not null,
  owner_name text not null,
  role_title text not null default '',
  slogan text not null default '',
  bio text not null default '',
  cta_label text not null default 'בואו נדבר',
  phone text not null default '',
  whatsapp text not null default '',
  email text not null default '',
  website text not null default '',
  address text not null default '',
  avatar_url text not null default '',
  cover_url text not null default '',
  logo_url text not null default '',
  logo_shape text not null default 'rounded' check (logo_shape in ('circle', 'rounded', 'square')),
  video_url text not null default '',
  gallery jsonb not null default '[]'::jsonb,
  files jsonb not null default '[]'::jsonb,
  primary_color text not null default '#6d4aff',
  accent_color text not null default '#14d9c4',
  button_color text not null default '#6d4aff',
  heading_color text not null default '#142038',
  body_text_color text not null default '#53627a',
  background_preset text not null default 'aurora' check (background_preset in ('aurora', 'midnight', 'paper', 'sunset', 'ocean', 'minimal')),
  template text not null default 'spotlight' check (template in ('spotlight', 'clean', 'bold')),
  is_published boolean not null default false,
  allow_indexing boolean not null default true,
  seo_title text not null default '',
  seo_description text not null default '',
  social_image_url text not null default '',
  area_served text not null default '',
  cover_alt text not null default '',
  logo_alt text not null default '',
  avatar_alt text not null default '',
  social_links jsonb not null default '[]'::jsonb,
  quick_actions jsonb not null default '[]'::jsonb,
  quick_actions_limit smallint not null default 6 check (quick_actions_limit in (3, 6, 9)),
  smart_buttons jsonb not null default '[]'::jsonb,
  widgets jsonb not null default '[]'::jsonb,
  contact_form_title text not null default 'רוצה שנחזור אליך?',
  contact_form_success_message text not null default 'תודה! הפרטים התקבלו.',
  contact_form_fields jsonb not null default '[]'::jsonb,
  gallery_style text not null default 'grid' check (gallery_style in ('grid', 'carousel')),
  tracking jsonb not null default '{"googleAnalyticsId":"","googleTagManagerId":"","metaPixelId":""}'::jsonb,
  vcard jsonb not null default '{}'::jsonb,
  services jsonb not null default '[]'::jsonb,
  testimonials jsonb not null default '[]'::jsonb,
  business_hours jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.card_events (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.cards(id) on delete cascade,
  event_type text not null check (event_type in ('view', 'qr_scan', 'phone', 'whatsapp', 'whatsapp_primary', 'email', 'contact_save', 'map', 'waze', 'google_maps', 'website', 'share', 'social', 'instagram', 'facebook', 'linkedin', 'tiktok', 'youtube', 'calendar', 'button', 'video', 'file', 'lead')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  name text not null,
  phone text not null,
  email text,
  message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  plan_id text not null default 'trial' check (plan_id in ('trial', 'basic', 'pro', 'premium')),
  status text not null default 'trialing' check (status in ('trialing', 'active', 'past_due', 'canceled')),
  provider text not null default 'manual',
  provider_customer_id text,
  provider_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_events (
  id text primary key,
  event_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists cards_user_id_idx on public.cards(user_id);
create index if not exists cards_published_slug_idx on public.cards(slug) where is_published = true;
create index if not exists card_events_card_created_idx on public.card_events(card_id, created_at desc);
create index if not exists card_events_type_idx on public.card_events(card_id, event_type);
create index if not exists leads_card_created_idx on public.leads(card_id, created_at desc);
create index if not exists leads_status_idx on public.leads(card_id, status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists cards_set_updated_at on public.cards;
create trigger cards_set_updated_at before update on public.cards for each row execute function public.set_updated_at();
drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at before update on public.leads for each row execute function public.set_updated_at();
drop trigger if exists subscriptions_set_updated_at on public.subscriptions;
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'full_name', ''));

  insert into public.subscriptions (user_id, plan_id, status, provider, current_period_end)
  values (new.id, 'trial', 'trialing', 'trial', now() + interval '14 days');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.cards enable row level security;
alter table public.card_events enable row level security;
alter table public.leads enable row level security;
alter table public.subscriptions enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.payment_events enable row level security;

create policy "profiles_read_own" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles_update_own" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles_admin_all" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "cards_public_read_published" on public.cards for select to anon, authenticated using (is_published = true or user_id = auth.uid() or public.is_admin());
create policy "cards_owner_insert" on public.cards for insert to authenticated with check (user_id = auth.uid());
create policy "cards_owner_update" on public.cards for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "cards_owner_delete" on public.cards for delete to authenticated using (user_id = auth.uid() or public.is_admin());

create policy "events_owner_read" on public.card_events for select to authenticated using (exists(select 1 from public.cards where cards.id = card_events.card_id and (cards.user_id = auth.uid() or public.is_admin())));
create policy "leads_owner_read" on public.leads for select to authenticated using (exists(select 1 from public.cards where cards.id = leads.card_id and (cards.user_id = auth.uid() or public.is_admin())));
create policy "leads_owner_update" on public.leads for update to authenticated using (exists(select 1 from public.cards where cards.id = leads.card_id and (cards.user_id = auth.uid() or public.is_admin()))) with check (exists(select 1 from public.cards where cards.id = leads.card_id and (cards.user_id = auth.uid() or public.is_admin())));
create policy "subscriptions_read_own" on public.subscriptions for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "audit_admin_read" on public.admin_audit_log for select to authenticated using (public.is_admin());
create policy "payment_events_admin_read" on public.payment_events for select to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('card-media', 'card-media', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "card_media_public_read" on storage.objects for select to public using (bucket_id = 'card-media');
create policy "card_media_owner_insert" on storage.objects for insert to authenticated with check (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "card_media_owner_update" on storage.objects for update to authenticated using (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "card_media_owner_delete" on storage.objects for delete to authenticated using (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text);

grant execute on function public.is_admin() to authenticated;
revoke update on public.profiles from authenticated;
grant update (full_name, updated_at) on public.profiles to authenticated;

-- ----------------------------------------------------------------
-- 002_naimly_seo_accessibility.sql
-- ----------------------------------------------------------------

alter table public.cards add column if not exists allow_indexing boolean not null default true;
alter table public.cards add column if not exists social_image_url text not null default '';
alter table public.cards add column if not exists area_served text not null default '';
alter table public.cards add column if not exists cover_alt text not null default '';
alter table public.cards add column if not exists logo_alt text not null default '';
alter table public.cards add column if not exists avatar_alt text not null default '';

alter table public.card_events drop constraint if exists card_events_event_type_check;
alter table public.card_events add constraint card_events_event_type_check check (
  event_type in ('view', 'qr_scan', 'phone', 'whatsapp', 'whatsapp_primary', 'email', 'contact_save', 'map', 'waze', 'google_maps', 'website', 'share', 'social', 'instagram', 'facebook', 'linkedin', 'tiktok', 'youtube', 'calendar', 'button', 'video', 'file', 'lead')
);

-- ----------------------------------------------------------------
-- 003_plan_enforcement.sql
-- ----------------------------------------------------------------

-- אכיפת מסלולים ותקופת התנסות ברמת מסד הנתונים.
--
-- הרקע: /api/cards כותב עם ה‑session של המשתמש ומפתח ה‑anon הציבורי. לכן כל
-- לקוח יכול לפנות ישירות ל‑PostgREST ולעקוף את בדיקות המסלול שמבוצעות ב‑route.
-- הבדיקות כאן הן הגבול האמיתי; ה‑UI וה‑API רק משקפים אותן.

-- 1. מגבלות לכל מסלול, במקום אחד. חייב להישאר תואם ל‑src/lib/config.ts
--    ול‑src/lib/plan-access.ts.
create table if not exists public.plan_limits (
  plan_id text primary key check (plan_id in ('trial', 'basic', 'pro', 'premium')),
  max_cards smallint not null,
  max_gallery_items smallint not null,
  max_quick_actions smallint not null,
  max_files smallint not null,
  analytics_days integer not null,
  allow_tracking boolean not null,
  allow_carousel boolean not null,
  allow_video boolean not null,
  allow_files boolean not null,
  allow_lead_export boolean not null,
  allow_advanced_seo boolean not null default false
);

alter table public.plan_limits add column if not exists allow_advanced_seo boolean not null default false;

insert into public.plan_limits (plan_id, max_cards, max_gallery_items, max_quick_actions, max_files, analytics_days, allow_tracking, allow_carousel, allow_video, allow_files, allow_lead_export, allow_advanced_seo)
values
  ('trial',   1, 3,   3, 0,  7,   false, false, false, false, false, false),
  ('basic',   1, 10,  3, 0,  30,  false, false, true,  false, false, false),
  ('pro',     1, 30,  6, 10, 365, true,  true,  true,  true,  false, true),
  ('premium', 1, 100, 9, 30, 730, true,  true,  true,  true,  true,  true)
on conflict (plan_id) do update set
  max_cards = excluded.max_cards,
  max_gallery_items = excluded.max_gallery_items,
  max_quick_actions = excluded.max_quick_actions,
  max_files = excluded.max_files,
  analytics_days = excluded.analytics_days,
  allow_tracking = excluded.allow_tracking,
  allow_carousel = excluded.allow_carousel,
  allow_video = excluded.allow_video,
  allow_files = excluded.allow_files,
  allow_lead_export = excluded.allow_lead_export,
  allow_advanced_seo = excluded.allow_advanced_seo;

alter table public.plan_limits enable row level security;
drop policy if exists "plan_limits_public_read" on public.plan_limits;
create policy "plan_limits_public_read" on public.plan_limits for select to anon, authenticated using (true);

-- 2. המסלול האפקטיבי של משתמש: המנוי קובע, ורק כשהוא בתוקף.
--    התנסות שפג תוקפה חוזרת ל‑'trial' ומאבדת את הרשאת הפרסום.
create or replace function public.effective_plan(target_user uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when s.status = 'active' then s.plan_id
    when s.status = 'trialing' and s.current_period_end > now() then s.plan_id
    else 'trial'
  end
  from public.subscriptions s
  where s.user_id = target_user;
$$;

create or replace function public.subscription_live(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select s.status = 'active' or (s.status = 'trialing' and s.current_period_end > now())
     from public.subscriptions s where s.user_id = target_user),
    false);
$$;

grant execute on function public.effective_plan(uuid) to authenticated;
grant execute on function public.subscription_live(uuid) to anon, authenticated;

-- 3. הטריגר שאוכף בפועל. פועל על insert ועל update של cards.
create or replace function public.enforce_plan_limits()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  plan text;
  lim public.plan_limits%rowtype;
  card_count integer;
  widget_types text[];
begin
  -- כתיבה עם service-role (webhook, כלי ניהול) עוקפת את האכיפה במכוון.
  if auth.uid() is null then
    return new;
  end if;

  plan := coalesce(public.effective_plan(new.user_id), 'trial');
  select * into lim from public.plan_limits where plan_id = plan;
  if not found then
    select * into lim from public.plan_limits where plan_id = 'trial';
  end if;

  if not public.subscription_live(new.user_id) and new.is_published then
    raise exception 'PLAN_LIMIT:subscription:תקופת ההתנסות הסתיימה. יש לבחור מסלול כדי לפרסם את הכרטיס.'
      using errcode = 'check_violation';
  end if;

  if tg_op = 'INSERT' then
    select count(*) into card_count from public.cards where user_id = new.user_id;
    if card_count >= lim.max_cards then
      raise exception 'PLAN_LIMIT:cards:המסלול הנוכחי מאפשר עד % כרטיסים.', lim.max_cards
        using errcode = 'check_violation';
    end if;
  end if;

  if jsonb_array_length(coalesce(new.gallery, '[]'::jsonb)) > lim.max_gallery_items then
    raise exception 'PLAN_LIMIT:gallery:המסלול הנוכחי מאפשר עד % תמונות בגלריה.', lim.max_gallery_items
      using errcode = 'check_violation';
  end if;

  if jsonb_array_length(coalesce(new.quick_actions, '[]'::jsonb)) > lim.max_quick_actions
     or new.quick_actions_limit > lim.max_quick_actions then
    raise exception 'PLAN_LIMIT:quickActions:המסלול הנוכחי מאפשר עד % פעולות מהירות.', lim.max_quick_actions
      using errcode = 'check_violation';
  end if;

  if not lim.allow_tracking and concat(
       new.tracking ->> 'googleAnalyticsId',
       new.tracking ->> 'googleTagManagerId',
       new.tracking ->> 'metaPixelId') <> '' then
    raise exception 'PLAN_LIMIT:tracking:חיבור Meta Pixel ו-Google Analytics זמין במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if not lim.allow_advanced_seo and (coalesce(new.area_served, '') <> '' or coalesce(new.social_image_url, '') <> '') then
    raise exception 'PLAN_LIMIT:seo:אזור שירות ותמונת שיתוף מותאמת זמינים במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if not lim.allow_carousel and new.gallery_style = 'carousel' then
    raise exception 'PLAN_LIMIT:carousel:גלריית קרוסלה זמינה במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  select array_agg(value ->> 'type') into widget_types
  from jsonb_array_elements(coalesce(new.widgets, '[]'::jsonb))
  where (value ->> 'enabled')::boolean is true;

  if not lim.allow_video and 'video' = any(coalesce(widget_types, array[]::text[])) then
    raise exception 'PLAN_LIMIT:video:וידג׳ט הסרטון זמין במסלול בסיסי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if not lim.allow_files and (jsonb_array_length(coalesce(new.files, '[]'::jsonb)) > 0
       or 'files' = any(coalesce(widget_types, array[]::text[]))) then
    raise exception 'PLAN_LIMIT:files:צירוף קבצים להורדה זמין במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if jsonb_array_length(coalesce(new.files, '[]'::jsonb)) > lim.max_files then
    raise exception 'PLAN_LIMIT:files:המסלול הנוכחי מאפשר עד % קבצים.', lim.max_files
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists cards_enforce_plan_limits on public.cards;
create trigger cards_enforce_plan_limits
  before insert or update on public.cards
  for each row execute function public.enforce_plan_limits();

-- 4. חסימת שינוי בעלות על כרטיס קיים.
create or replace function public.lock_card_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is not null and new.user_id is distinct from old.user_id then
    raise exception 'לא ניתן להעביר בעלות על כרטיס.' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists cards_lock_owner on public.cards;
create trigger cards_lock_owner before update on public.cards
  for each row execute function public.lock_card_owner();

-- 5. קריאה ציבורית של כרטיס מוגבלת לבעלי מנוי בתוקף, בהתאמה ל‑getPublicCard.
drop policy if exists "cards_public_read_published" on public.cards;
create policy "cards_public_read_published" on public.cards
  for select to anon, authenticated
  using (
    user_id = auth.uid()
    or public.is_admin()
    or (is_published = true and public.subscription_live(user_id))
  );

-- 6. ההתנסות מקבלת חותמות זמן מפורשות, כדי שהטיימר בממשק יציג נתון אמיתי
--    ולא יסתמך על current_period_end בלבד.
alter table public.subscriptions add column if not exists trial_started_at timestamptz;
alter table public.subscriptions add column if not exists trial_ends_at timestamptz;

update public.subscriptions
set trial_ends_at = coalesce(trial_ends_at, current_period_end),
    trial_started_at = coalesce(trial_started_at, created_at)
where provider = 'trial' or status = 'trialing';

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;

  insert into public.subscriptions (user_id, plan_id, status, provider, current_period_end, trial_started_at, trial_ends_at)
  values (new.id, 'trial', 'trialing', 'trial', now() + interval '14 days', now(), now() + interval '14 days')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

-- 7. אינדקסים לשאילתות שנוספו.
create index if not exists subscriptions_status_idx on public.subscriptions(status, current_period_end);

-- ----------------------------------------------------------------
-- 004_bit_payments_and_approvals.sql
-- ----------------------------------------------------------------

-- תשלום בביט דרך וואטסאפ + אישור ידני של מנהל, והתנסות עם גישה מלאה.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. ההתנסות פותחת את כל היכולות, במכסות של פרימיום.
--    כשההתנסות מסתיימת ללא תשלום, effective_plan מחזיר 'none' והכול נחסם.
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.plan_limits (plan_id, max_cards, max_gallery_items, max_quick_actions, max_files, analytics_days, allow_tracking, allow_carousel, allow_video, allow_files, allow_lead_export, allow_advanced_seo)
values ('trial', 1, 100, 9, 30, 730, true, true, true, true, true, true)
on conflict (plan_id) do update set
  max_gallery_items = excluded.max_gallery_items,
  max_quick_actions = excluded.max_quick_actions,
  max_files = excluded.max_files,
  analytics_days = excluded.analytics_days,
  allow_tracking = excluded.allow_tracking,
  allow_carousel = excluded.allow_carousel,
  allow_video = excluded.allow_video,
  allow_files = excluded.allow_files,
  allow_lead_export = excluded.allow_lead_export,
  allow_advanced_seo = excluded.allow_advanced_seo;

-- מסלול 'none' = לא שילם. אפס יכולות; משמש כשההתנסות פגה.
insert into public.plan_limits (plan_id, max_cards, max_gallery_items, max_quick_actions, max_files, analytics_days, allow_tracking, allow_carousel, allow_video, allow_files, allow_lead_export, allow_advanced_seo)
values ('none', 0, 0, 3, 0, 0, false, false, false, false, false, false)
on conflict (plan_id) do nothing;

alter table public.plan_limits drop constraint if exists plan_limits_plan_id_check;
alter table public.plan_limits add constraint plan_limits_plan_id_check
  check (plan_id in ('none', 'trial', 'basic', 'pro', 'premium'));

create or replace function public.effective_plan(target_user uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select case
      when s.status = 'active' then s.plan_id
      when s.status = 'trialing' and s.current_period_end > now() then 'trial'
      else 'none'
    end
    from public.subscriptions s
    where s.user_id = target_user
  ), 'none');
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. כשלא שילם — הכול נחסם, לא רק הפרסום.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.enforce_plan_limits()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  plan text;
  lim public.plan_limits%rowtype;
  card_count integer;
  widget_types text[];
begin
  -- כתיבה עם service-role (webhook, אישור מנהל, כלי ניהול) עוקפת במכוון.
  if auth.uid() is null then
    return new;
  end if;

  plan := public.effective_plan(new.user_id);

  if plan = 'none' then
    raise exception 'PLAN_LIMIT:subscription:אין מנוי פעיל. יש לבחור מסלול ולהשלים תשלום כדי לערוך את הכרטיס.'
      using errcode = 'check_violation';
  end if;

  select * into lim from public.plan_limits where plan_id = plan;
  if not found then
    select * into lim from public.plan_limits where plan_id = 'basic';
  end if;

  if tg_op = 'INSERT' then
    select count(*) into card_count from public.cards where user_id = new.user_id;
    if card_count >= lim.max_cards then
      raise exception 'PLAN_LIMIT:cards:המסלול הנוכחי מאפשר עד % כרטיסים.', lim.max_cards
        using errcode = 'check_violation';
    end if;
  end if;

  if jsonb_array_length(coalesce(new.gallery, '[]'::jsonb)) > lim.max_gallery_items then
    raise exception 'PLAN_LIMIT:gallery:המסלול הנוכחי מאפשר עד % תמונות בגלריה.', lim.max_gallery_items
      using errcode = 'check_violation';
  end if;

  if jsonb_array_length(coalesce(new.quick_actions, '[]'::jsonb)) > lim.max_quick_actions
     or new.quick_actions_limit > lim.max_quick_actions then
    raise exception 'PLAN_LIMIT:quickActions:המסלול הנוכחי מאפשר עד % פעולות מהירות.', lim.max_quick_actions
      using errcode = 'check_violation';
  end if;

  if not lim.allow_tracking and concat(
       new.tracking ->> 'googleAnalyticsId',
       new.tracking ->> 'googleTagManagerId',
       new.tracking ->> 'metaPixelId') <> '' then
    raise exception 'PLAN_LIMIT:tracking:חיבור Meta Pixel ו-Google Analytics זמין במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if not lim.allow_advanced_seo and (coalesce(new.area_served, '') <> '' or coalesce(new.social_image_url, '') <> '') then
    raise exception 'PLAN_LIMIT:seo:אזור שירות ותמונת שיתוף מותאמת זמינים במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if not lim.allow_carousel and new.gallery_style = 'carousel' then
    raise exception 'PLAN_LIMIT:carousel:גלריית קרוסלה זמינה במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  select array_agg(value ->> 'type') into widget_types
  from jsonb_array_elements(coalesce(new.widgets, '[]'::jsonb))
  where (value ->> 'enabled')::boolean is true;

  if not lim.allow_video and 'video' = any(coalesce(widget_types, array[]::text[])) then
    raise exception 'PLAN_LIMIT:video:וידג׳ט הסרטון זמין במסלול בסיסי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if not lim.allow_files and (jsonb_array_length(coalesce(new.files, '[]'::jsonb)) > 0
       or 'files' = any(coalesce(widget_types, array[]::text[]))) then
    raise exception 'PLAN_LIMIT:files:צירוף קבצים להורדה זמין במסלול מקצועי ומעלה.'
      using errcode = 'check_violation';
  end if;

  if jsonb_array_length(coalesce(new.files, '[]'::jsonb)) > lim.max_files then
    raise exception 'PLAN_LIMIT:files:המסלול הנוכחי מאפשר עד % קבצים.', lim.max_files
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. בקשות תשלום (ביט/וואטסאפ) שממתינות לאישור מנהל.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.payment_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  reference text not null unique,
  plan_id text not null check (plan_id in ('basic', 'pro', 'premium')),
  amount numeric(10, 2) not null,
  method text not null default 'bit' check (method in ('bit', 'bank_transfer', 'cash', 'other')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'canceled')),
  contact_phone text not null default '',
  note text not null default '',
  admin_note text not null default '',
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_requests_status_idx on public.payment_requests(status, created_at desc);
create index if not exists payment_requests_user_idx on public.payment_requests(user_id, created_at desc);

drop trigger if exists payment_requests_set_updated_at on public.payment_requests;
create trigger payment_requests_set_updated_at before update on public.payment_requests
  for each row execute function public.set_updated_at();

alter table public.payment_requests enable row level security;

-- הלקוח רואה רק את הבקשות שלו. יצירה ואישור עוברים דרך ה־API בלבד.
drop policy if exists "payment_requests_read_own" on public.payment_requests;
create policy "payment_requests_read_own" on public.payment_requests
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. פרופיל: מספר וואטסאפ לשליחת פרטי התחברות, וסימון אישור ידני.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.profiles add column if not exists phone text not null default '';
alter table public.profiles add column if not exists approved_at timestamptz;
alter table public.profiles add column if not exists credentials_sent_at timestamptz;
alter table public.profiles add column if not exists created_by_admin boolean not null default false;

grant update (full_name, phone, updated_at) on public.profiles to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. הפעלת מנוי לאחר אישור מנהל — פונקציה אחת שמרכזת את כל השינויים.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.activate_subscription(
  target_user uuid,
  target_plan text,
  months integer default 1,
  actor uuid default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.subscriptions (user_id, plan_id, status, provider, current_period_end)
  values (target_user, target_plan, 'active', 'bit', now() + (months || ' months')::interval)
  on conflict (user_id) do update set
    plan_id = excluded.plan_id,
    status = 'active',
    provider = 'bit',
    current_period_end = excluded.current_period_end,
    updated_at = now();

  update public.profiles
  set plan_id = target_plan, approved_at = coalesce(approved_at, now()), updated_at = now()
  where id = target_user;

  insert into public.admin_audit_log (actor_id, action, entity_type, entity_id, details)
  values (actor, 'subscription.activate', 'user', target_user::text,
          jsonb_build_object('plan', target_plan, 'months', months));
end;
$$;

revoke execute on function public.activate_subscription(uuid, text, integer, uuid) from public, anon, authenticated;

-- ----------------------------------------------------------------
-- 005_contact_messages.sql
-- ----------------------------------------------------------------

-- פניות מטופס "צרו קשר" באתר.

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  topic text not null check (topic in ('improvement', 'sales', 'training', 'technical', 'general')),
  topic_label text not null default '',
  priority text not null default 'low' check (priority in ('low', 'normal', 'high')),
  name text not null,
  email text not null,
  phone text not null default '',
  message text not null,
  -- מזהה המשתמש כשהפנייה נשלחה ממשתמש מחובר. אחרת null.
  user_id uuid references public.profiles(id) on delete set null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'closed')),
  admin_note text not null default '',
  handled_by uuid references public.profiles(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contact_messages_status_idx on public.contact_messages(status, priority desc, created_at desc);
create index if not exists contact_messages_user_idx on public.contact_messages(user_id, created_at desc);

drop trigger if exists contact_messages_set_updated_at on public.contact_messages;
create trigger contact_messages_set_updated_at before update on public.contact_messages
  for each row execute function public.set_updated_at();

alter table public.contact_messages enable row level security;

-- כתיבה מתבצעת רק דרך ה-API עם service-role. קריאה: המנהל, או השולח את שלו.
drop policy if exists "contact_messages_read" on public.contact_messages;
create policy "contact_messages_read" on public.contact_messages
  for select to authenticated
  using (public.is_admin() or user_id = auth.uid());

-- ----------------------------------------------------------------
-- 006_background_library.sql
-- ----------------------------------------------------------------

-- ספריית רקעים מורחבת.
--
-- המגבלה המקורית התירה שישה ערכים בלבד, ולכן כל רקע חדש היה נדחה על ידי
-- מסד הנתונים. במקום רשימה קשיחה ב-check, הרקעים עוברים לטבלת lookup —
-- כך אפשר להוסיף רקעים בלי מיגרציה נוספת, וההגנה נשמרת דרך מפתח זר.

create table if not exists public.card_backgrounds (
  id text primary key,
  name text not null,
  category text not null check (category in (
    'professional', 'minimal', 'luxury', 'colorful', 'dark',
    'light', 'tech', 'creative', 'gradient', 'geometric'
  )),
  -- 'dark' = טקסט כהה מעל הרקע, 'light' = טקסט בהיר.
  foreground text not null default 'dark' check (foreground in ('dark', 'light')),
  is_active boolean not null default true,
  sort_order smallint not null default 0
);

alter table public.card_backgrounds enable row level security;

drop policy if exists "card_backgrounds_public_read" on public.card_backgrounds;
create policy "card_backgrounds_public_read" on public.card_backgrounds
  for select to anon, authenticated using (true);

-- הרקעים עצמם נשמרים בקוד (src/lib/backgrounds.ts) כדי שה-CSS יהיה
-- זהה בין התצוגה המקדימה לכרטיס המפורסם. הטבלה מחזיקה רק את המזהים,
-- לצורך אימות ברמת מסד הנתונים.
insert into public.card_backgrounds (id, name, category, foreground, sort_order) values
  ('aurora', 'אורורה', 'professional', 'dark', 1),
  ('corporate-slate', 'אפור עסקי', 'professional', 'dark', 2),
  ('trust-blue', 'כחול אמון', 'professional', 'dark', 3),
  ('consultant-sand', 'חול יועץ', 'professional', 'dark', 4),
  ('legal-navy', 'נייבי משפטי', 'professional', 'light', 5),
  ('medical-mint', 'מנטה רפואי', 'professional', 'dark', 6),
  ('minimal', 'מינימלי', 'minimal', 'dark', 7),
  ('pure-white', 'לבן נקי', 'minimal', 'dark', 8),
  ('paper', 'נייר', 'minimal', 'dark', 9),
  ('fog', 'ערפל', 'minimal', 'dark', 10),
  ('linen', 'פשתן', 'minimal', 'dark', 11),
  ('whisper-grey', 'אפור לחישה', 'minimal', 'dark', 12),
  ('black-gold', 'שחור וזהב', 'luxury', 'light', 13),
  ('champagne', 'שמפניה', 'luxury', 'dark', 14),
  ('royal-purple', 'סגול מלכותי', 'luxury', 'light', 15),
  ('emerald-velvet', 'קטיפה אמרלד', 'luxury', 'light', 16),
  ('rose-marble', 'שיש רוזה', 'luxury', 'dark', 17),
  ('obsidian', 'אובסידיאן', 'luxury', 'light', 18),
  ('sunset', 'שקיעה', 'colorful', 'dark', 19),
  ('citrus', 'הדרים', 'colorful', 'dark', 20),
  ('tropical', 'טרופי', 'colorful', 'dark', 21),
  ('candy', 'סוכריה', 'colorful', 'dark', 22),
  ('rainbow-soft', 'קשת רכה', 'colorful', 'dark', 23),
  ('coral-reef', 'שונית אלמוגים', 'colorful', 'dark', 24),
  ('midnight', 'חצות', 'dark', 'light', 25),
  ('ocean', 'אוקיינוס', 'dark', 'light', 26),
  ('charcoal', 'פחם', 'dark', 'light', 27),
  ('deep-forest', 'יער עמוק', 'dark', 'light', 28),
  ('wine', 'יין', 'dark', 'light', 29),
  ('space', 'חלל', 'dark', 'light', 30),
  ('daylight', 'אור יום', 'light', 'dark', 31),
  ('sky', 'שמיים', 'light', 'dark', 32),
  ('peach-soft', 'אפרסק רך', 'light', 'dark', 33),
  ('mint-light', 'מנטה בהיר', 'light', 'dark', 34),
  ('lavender-light', 'לבנדר בהיר', 'light', 'dark', 35),
  ('butter', 'חמאה', 'light', 'dark', 36),
  ('circuit', 'מעגלים', 'tech', 'light', 37),
  ('neon-grid', 'רשת ניאון', 'tech', 'light', 38),
  ('data-blue', 'כחול דאטה', 'tech', 'light', 39),
  ('terminal', 'טרמינל', 'tech', 'light', 40),
  ('chrome', 'כרום', 'tech', 'dark', 41),
  ('hologram', 'הולוגרמה', 'tech', 'dark', 42),
  ('watercolor', 'צבעי מים', 'creative', 'dark', 43),
  ('ink-splash', 'כתם דיו', 'creative', 'light', 44),
  ('sunrise-studio', 'סטודיו זריחה', 'creative', 'dark', 45),
  ('pastel-dream', 'חלום פסטל', 'creative', 'dark', 46),
  ('duotone-violet', 'דואוטון סגול', 'creative', 'light', 47),
  ('canvas-texture', 'מרקם בד', 'creative', 'dark', 48),
  ('soft-violet', 'סגול רך', 'gradient', 'dark', 49),
  ('soft-teal', 'טורקיז רך', 'gradient', 'dark', 50),
  ('soft-rose', 'רוזה רך', 'gradient', 'dark', 51),
  ('soft-amber', 'אמבר רך', 'gradient', 'dark', 52),
  ('aurora-mesh', 'רשת אורורה', 'gradient', 'dark', 53),
  ('twilight-fade', 'דמדומים', 'gradient', 'light', 54),
  ('diagonal-stripes', 'פסים אלכסוניים', 'geometric', 'dark', 55),
  ('dot-grid', 'רשת נקודות', 'geometric', 'dark', 56),
  ('blueprint', 'שרטוט', 'geometric', 'dark', 57),
  ('hex-mesh', 'משושים', 'geometric', 'dark', 58),
  ('arc-layers', 'שכבות קשת', 'geometric', 'light', 59),
  ('checker-soft', 'משבצות רכות', 'geometric', 'dark', 60)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  foreground = excluded.foreground,
  sort_order = excluded.sort_order,
  is_active = true;

-- המגבלה הקשיחה מוסרת ומוחלפת במפתח זר לטבלת הרקעים.
alter table public.cards drop constraint if exists cards_background_preset_check;
alter table public.cards drop constraint if exists cards_background_preset_fkey;
alter table public.cards
  add constraint cards_background_preset_fkey
  foreign key (background_preset) references public.card_backgrounds(id)
  on update cascade on delete set default;

create index if not exists cards_background_idx on public.cards(background_preset);
