-- NAIMLY: סכמת Production ראשונית ל-Supabase/PostgreSQL
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  full_name text not null default '',
  role text not null default 'customer' check (role in ('customer', 'admin')),
  plan_id text not null default 'trial' check (plan_id in ('trial', 'basic', 'pro', 'premium')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9-]{3,60}$'),
  business_name text not null,
  owner_name text not null,
  role_title text not null default '',
  slogan text not null default '',
  bio text not null default '',
  cta_label text not null default 'בואו נדבר',
  phone text not null default '',
  whatsapp text not null default '',
  email text not null default '',
  website text not null default '',
  address text not null default '',
  avatar_url text not null default '',
  cover_url text not null default '',
  logo_url text not null default '',
  logo_shape text not null default 'rounded' check (logo_shape in ('circle', 'rounded', 'square')),
  video_url text not null default '',
  gallery jsonb not null default '[]'::jsonb,
  files jsonb not null default '[]'::jsonb,
  primary_color text not null default '#6d4aff',
  accent_color text not null default '#14d9c4',
  button_color text not null default '#6d4aff',
  heading_color text not null default '#142038',
  body_text_color text not null default '#53627a',
  background_preset text not null default 'aurora' check (background_preset in ('aurora', 'midnight', 'paper', 'sunset', 'ocean', 'minimal')),
  template text not null default 'spotlight' check (template in ('spotlight', 'clean', 'bold')),
  is_published boolean not null default false,
  allow_indexing boolean not null default true,
  seo_title text not null default '',
  seo_description text not null default '',
  social_image_url text not null default '',
  area_served text not null default '',
  cover_alt text not null default '',
  logo_alt text not null default '',
  avatar_alt text not null default '',
  social_links jsonb not null default '[]'::jsonb,
  quick_actions jsonb not null default '[]'::jsonb,
  quick_actions_limit smallint not null default 6 check (quick_actions_limit in (3, 6, 9)),
  smart_buttons jsonb not null default '[]'::jsonb,
  widgets jsonb not null default '[]'::jsonb,
  contact_form_title text not null default 'רוצה שנחזור אליך?',
  contact_form_success_message text not null default 'תודה! הפרטים התקבלו.',
  contact_form_fields jsonb not null default '[]'::jsonb,
  gallery_style text not null default 'grid' check (gallery_style in ('grid', 'carousel')),
  tracking jsonb not null default '{"googleAnalyticsId":"","googleTagManagerId":"","metaPixelId":""}'::jsonb,
  vcard jsonb not null default '{}'::jsonb,
  services jsonb not null default '[]'::jsonb,
  testimonials jsonb not null default '[]'::jsonb,
  business_hours jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.card_events (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.cards(id) on delete cascade,
  event_type text not null check (event_type in ('view', 'qr_scan', 'phone', 'whatsapp', 'whatsapp_primary', 'email', 'contact_save', 'map', 'waze', 'google_maps', 'website', 'share', 'social', 'instagram', 'facebook', 'linkedin', 'tiktok', 'youtube', 'calendar', 'button', 'video', 'file', 'lead')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  name text not null,
  phone text not null,
  email text,
  message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  plan_id text not null default 'trial' check (plan_id in ('trial', 'basic', 'pro', 'premium')),
  status text not null default 'trialing' check (status in ('trialing', 'active', 'past_due', 'canceled')),
  provider text not null default 'manual',
  provider_customer_id text,
  provider_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_events (
  id text primary key,
  event_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists cards_user_id_idx on public.cards(user_id);
create index if not exists cards_published_slug_idx on public.cards(slug) where is_published = true;
create index if not exists card_events_card_created_idx on public.card_events(card_id, created_at desc);
create index if not exists card_events_type_idx on public.card_events(card_id, event_type);
create index if not exists leads_card_created_idx on public.leads(card_id, created_at desc);
create index if not exists leads_status_idx on public.leads(card_id, status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists cards_set_updated_at on public.cards;
create trigger cards_set_updated_at before update on public.cards for each row execute function public.set_updated_at();
drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at before update on public.leads for each row execute function public.set_updated_at();
drop trigger if exists subscriptions_set_updated_at on public.subscriptions;
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'full_name', ''));

  insert into public.subscriptions (user_id, plan_id, status, provider, current_period_end)
  values (new.id, 'trial', 'trialing', 'trial', now() + interval '14 days');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.cards enable row level security;
alter table public.card_events enable row level security;
alter table public.leads enable row level security;
alter table public.subscriptions enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.payment_events enable row level security;

create policy "profiles_read_own" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles_update_own" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles_admin_all" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "cards_public_read_published" on public.cards for select to anon, authenticated using (is_published = true or user_id = auth.uid() or public.is_admin());
create policy "cards_owner_insert" on public.cards for insert to authenticated with check (user_id = auth.uid());
create policy "cards_owner_update" on public.cards for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "cards_owner_delete" on public.cards for delete to authenticated using (user_id = auth.uid() or public.is_admin());

create policy "events_owner_read" on public.card_events for select to authenticated using (exists(select 1 from public.cards where cards.id = card_events.card_id and (cards.user_id = auth.uid() or public.is_admin())));
create policy "leads_owner_read" on public.leads for select to authenticated using (exists(select 1 from public.cards where cards.id = leads.card_id and (cards.user_id = auth.uid() or public.is_admin())));
create policy "leads_owner_update" on public.leads for update to authenticated using (exists(select 1 from public.cards where cards.id = leads.card_id and (cards.user_id = auth.uid() or public.is_admin()))) with check (exists(select 1 from public.cards where cards.id = leads.card_id and (cards.user_id = auth.uid() or public.is_admin())));
create policy "subscriptions_read_own" on public.subscriptions for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "audit_admin_read" on public.admin_audit_log for select to authenticated using (public.is_admin());
create policy "payment_events_admin_read" on public.payment_events for select to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('card-media', 'card-media', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "card_media_public_read" on storage.objects for select to public using (bucket_id = 'card-media');
create policy "card_media_owner_insert" on storage.objects for insert to authenticated with check (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "card_media_owner_update" on storage.objects for update to authenticated using (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "card_media_owner_delete" on storage.objects for delete to authenticated using (bucket_id = 'card-media' and (storage.foldername(name))[1] = auth.uid()::text);

grant execute on function public.is_admin() to authenticated;
revoke update on public.profiles from authenticated;
grant update (full_name, updated_at) on public.profiles to authenticated;
